spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: demo
  password: demo
  bpm:
    database:
      type: postgres
      table-prefix: camunda.
      schema-update: true

spring:
  profiles:
    active: development
  # Security configuration
  security:
    user:
      name: user
      password: user
  # Database

  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgres
    diver-class-name: ${DB_DRIVER}
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
#      spring.datasource.url: jdbc:postgresql://localhost:5432/postgres
#      spring.datasource.username: postgres
#      spring.datasource.password: postgres
#      spring.jpa.generate-ddl: true
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
# Server configuration
server:
  port: 8080

camunda:
  bpm:
    generic-properties:
      properties:
        userResourceWhitelistPattern: ".+"

#spring.datasource.url: jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username: postgres
#spring.datasource.password: postgres
#spring.jpa.generate-ddl: true